* `ngspice` Sim Input for `components.bias_gen.Tb`
* Generated by `vlsirtools.CompatibleNgspiceNetlister`
* 
* Anonymous `circuit.Package`
* Generated by `vlsirtools.CompatibleNgspiceNetlister`
* 

.SUBCKT BiasGen_f72424651aee556e1e66a6ccdc88a37b_
+ VDD VSS EN IBIAS1 IBIAS2 
* No parameters

rr_ref
+ VDD iref 
+ 1800000.0000000002
* No parameters


xm_ref
+ iref iref VSS VSS 
+ sky130_fd_pr__nfet_01v8
+ w='1' l='0.15' nf='1' ad='int((nf+1)/2) * w/nf * 0.29' As='int((nf+2)/2) * w/nf * 0.29' pd='2*int((nf+1)/2) * (w/nf + 0.29)' ps='2*int((nf+2)/2) * (w/nf + 0.29)' nrd='0.29 / w' nrs='0.29 / w' sa='0' sb='0' sd='0' mult='1' m='1' 

xm_out1
+ IBIAS1 iref VSS VSS 
+ sky130_fd_pr__nfet_01v8
+ w='1' l='0.15' nf='1' ad='int((nf+1)/2) * w/nf * 0.29' As='int((nf+2)/2) * w/nf * 0.29' pd='2*int((nf+1)/2) * (w/nf + 0.29)' ps='2*int((nf+2)/2) * (w/nf + 0.29)' nrd='0.29 / w' nrs='0.29 / w' sa='0' sb='0' sd='0' mult='1' m='1' 

xm_out2
+ IBIAS2 iref VSS VSS 
+ sky130_fd_pr__nfet_01v8
+ w='2' l='0.15' nf='1' ad='int((nf+1)/2) * w/nf * 0.29' As='int((nf+2)/2) * w/nf * 0.29' pd='2*int((nf+1)/2) * (w/nf + 0.29)' ps='2*int((nf+2)/2) * (w/nf + 0.29)' nrd='0.29 / w' nrs='0.29 / w' sa='0' sb='0' sd='0' mult='1' m='1' 

ren_bleed
+ EN VSS 
+ 1000000000
* No parameters


.ENDS

.SUBCKT Tb
+ VSS 
* No parameters

vvvdd
+ vdd VSS 
+ PULSE (0 1.8 0 2E-7 2E-7 0.00001 20u)
* No parameters


vven
+ en VSS 
+ DC 1.8
* No parameters


xxdut
+ vdd VSS en ibias1 ibias2 
+ BiasGen_f72424651aee556e1e66a6ccdc88a37b_
* No parameters


rrload1
+ vdd ibias1 
+ 200000
* No parameters


rrload2
+ vdd ibias2 
+ 200000
* No parameters


.ENDS

xtop 0 Tb // Top-Level DUT 


.save all
.lib "/home/vadim/work/eda-harness/pdks/sky130A/volare/sky130/versions/0fe599b2afb6708d281543108caf8310912f54af/sky130A/libs.tech/ngspice/sky130.lib.spice" tt
.tran 5e-08 1e-05




