* `ngspice` Sim Input for `components.current_mirror.Tb`
* Generated by `vlsirtools.CompatibleNgspiceNetlister`
* 
* Anonymous `circuit.Package`
* Generated by `vlsirtools.CompatibleNgspiceNetlister`
* 

.SUBCKT CurrentMirror_e669cf80b5b2ec3c574e6993c61c7011_
+ IN OUT VDD VSS 
* No parameters

xm_ref
+ IN IN VDD VDD 
+ sky130_fd_pr__pfet_01v8
+ w='1' l='0.15' nf='1' ad='int((nf+1)/2) * w/nf * 0.29' As='int((nf+2)/2) * w/nf * 0.29' pd='2*int((nf+1)/2) * (w/nf + 0.29)' ps='2*int((nf+2)/2) * (w/nf + 0.29)' nrd='0.29 / w' nrs='0.29 / w' sa='0' sb='0' sd='0' mult='1' m='1' 

xm_out
+ OUT IN VDD VDD 
+ sky130_fd_pr__pfet_01v8
+ w='1' l='0.15' nf='1' ad='int((nf+1)/2) * w/nf * 0.29' As='int((nf+2)/2) * w/nf * 0.29' pd='2*int((nf+1)/2) * (w/nf + 0.29)' ps='2*int((nf+2)/2) * (w/nf + 0.29)' nrd='0.29 / w' nrs='0.29 / w' sa='0' sb='0' sd='0' mult='1' m='1' 

.ENDS

.SUBCKT Tb
+ VSS 
* No parameters

vvvdd
+ vdd VSS 
+ DC 1.8
* No parameters


xxdut
+ inn out vdd VSS 
+ CurrentMirror_e669cf80b5b2ec3c574e6993c61c7011_
* No parameters


iiref
+ inn VSS 
+ 0.00002
* No parameters


rrload
+ out VSS 
+ 20000
* No parameters


.ENDS

xtop 0 Tb // Top-Level DUT 


.save all
.lib "/home/vadim/work/eda-harness/pdks/sky130A/volare/sky130/versions/0fe599b2afb6708d281543108caf8310912f54af/sky130A/libs.tech/ngspice/sky130.lib.spice" tt
.op




